version: "3.5"
services:
  infomer:
    build:
      dockerfile: informer/Dockerfile
      context: .
  proxy:
    build:
      dockerfile: proxy/Dockerfile
      context: .
  test:
    build:
      dockerfile: ops/Dockerfile
      context: .
    command: test
    entrypoint: cargo
