apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: openmetricsrules.open-metrics.vgs.io
spec:
  group: open-metrics.vgs.io
  names:
    kind: OpenMetricsRule
    plural: openmetricsrules
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          description: OpenMetricsRule CRD contains specification parameters for a
            Rule.
          properties:
            tenants:
              type: array
              items:
                type: string
            description:
              type: string
            groups:
              description: Content of Open Metrics rule file
              items:
                description: RuleGroup is a list of sequentially evaluated recording
                  and alerting rules.
                properties:
                  interval:
                    type: string
                  name:
                    type: string
                  rules:
                    items:
                      description: Open Metrics Rule describes an alerting or recording rule.
                      properties:
                        alert:
                          type: string
                        annotations:
                          type: object
                        expr:
                          type: string
                        for:
                          type: string
                        labels:
                          type: object
                        record:
                          type: string
                      required:
                        - expr
                    type: array
                required:
                  - name
                  - rules
              type: array
          required:
            - tenants
  version: v1
