apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ingestiontenants.open-metrics.vgs.io
spec:
  group: open-metrics.vgs.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                tenants:
                  type: array
                  items:
                    type: string
                description:
                  type: string
  scope: Namespaced
  names:
    plural: ingestiontenants
    singular: ingestiontenant
    kind: IngestionTenant
